
server:
  port: 8501
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    route-name:
      service-id: customer
      path: /user/**
  ignored-services: customer
